config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :offers do
      resources :images, controller: 'offer_images' do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/models/spree/offer.rb
module Spree
  class Offer < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :history

    has_many :images, -> { order(:position) }, class_name: 'Spree::OfferImage', as: :viewable, dependent: :destroy

    belongs_to :taxon, class_name: 'Spree::Taxon'

    validates :meta_keywords, length: { maximum: 255 }
    validates :meta_title, length: { maximum: 255 }
    validates :name, presence: true
    validates :taxon_id, presence: true
    validates :discount, numericality: { only_integer: true, greater_than: -1, less_than: 100 }
    validates :slug, length: { minimum: 3 }, uniqueness: { allow_blank: true }

    self.whitelisted_ransackable_associations = %w[stores images]
    self.whitelisted_ransackable_attributes = %w[slug]

    class << self
      def active
        where(active: true)
      end

      def main
        where(main: true)
      end

      def secondary
        where(main: false)
      end

      def with_discount
        where('discount > 0')
      end

      def without_discount
        where(discount: 0)
      end
    end

    def display_image
      images.first || Spree::OfferImage.new
    end

    private

    def slug_candidates
      [:name]
    end

  end
end

app/models/spree/offer_image.rb
module Spree
  class OfferImage < Asset
    validate :no_attachment_errors

    has_attached_file :attachment,
                      styles: { mini: '48x48>', small: '100x100>', r4x3: '800x600#',  r13x5: '1170x450#', r16x9: '942x530#' },
                      s3_protocol: Rails.env.production? ? :https : :http,
                      default_style: :offer,
                      default_url: 'noimage/:style.png',
                      url: '/spree/offers/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/offers/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :attachment,
      presence: true,
      content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    # used by admin offers autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do

  def offer_discount
    Spree::Offer.active.where(taxon_id: self.taxons.pluck(:id)).pluck(:discount).sort
  end

  def discount_price_for(price_options)
    # ((product_or_variant.price_for(current_pricing_options).to_d / 100.0) * (100.0 - discount.to_d)).to_s
    self.master.currently_valid_prices.detect do |price|
      discount_price = Spree::Price.new price.attributes
      discount_price.amount = discount_price.amount * (100 - offer_discount.last) / 100
      ( discount_price.country_iso == price_options.desired_attributes[:country_iso] ||
        discount_price.country_iso.nil?
      ) && discount_price.currency == price_options.desired_attributes[:currency]
      return discount_price.try!(:money)
    end.try!(:money)
  end

end

app/controllers/spree/admin/offer_images_controller.rb
module Spree
  module Admin
    class OfferImagesController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def index
      end

      private

      def model_class
        Spree::OfferImage
      end

      def location_after_destroy
        admin_offer_images_url(@offer)
      end

      def location_after_save
        admin_offer_images_url(@offer)
      end

      def load_data
        @offer = Spree::Offer.friendly.find(params[:offer_id])
      end

      def set_viewable
        @offer_image.viewable_type = 'Spree::Offer'
        @offer_image.viewable_id = params[:offer_image][:offer_id]
      end
    end
  end
end

app/controllers/spree/admin/offers_controller.rb
module Spree
  module Admin
    class OffersController < ResourceController

      before_action :available_taxons, only: [:index, :new, :edit]

      def index
        respond_with(@collection) do |format|
          format.html
        end
      end

      def show
        redirect_to edit_admin_offer_path(@offer)
      end

      def create
        @offer = Spree::Offer.new(offer_params)
        if @offer.save

          flash[:success] = Spree.t(:created_successfully)
          redirect_to edit_admin_offer_url(@offer)
        else
          render :new, status: :unprocessable_entity
        end
      end

      private

      def find_resource
        Spree::Offer.friendly.find(params[:id])
      end

      def collection
        return @collection if @collection.present?
        if request.xhr? && params[:q].present?
          @collection = Spree::Offer
          .where("spree_offers.title #{LIKE} :search",
                 { search: "#{params[:q].strip}%" })
          .limit(params[:limit] || 100)
        else
          @search = Spree::Offer.ransack(params[:q])
          @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_products_per_page])
        end
      end

      def offer_params
        attributes = [:name, :abstract, :description, :meta_title, :meta_description, :meta_keywords,
                      :slug, :discount, :active, :main, :taxon_id]

        params.require(:offer).permit(attributes)
      end

      def available_taxons
        taxon_hash = {}
        @taxons = Spree::Taxon.all.order(:taxonomy_id, :lft).map do |t|
          if t.parent_id.nil?
            taxon_hash[t.id] = t.name
          else
            taxon_hash[t.id] = "#{taxon_hash[t.parent_id]} > #{t.name}"
          end
          [t.id, taxon_hash[t.id]]
        end
      end
    end
  end
end

app/views/spree/admin/offer_images/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label :attachment %><br>
      <%= f.file_field :attachment %>
    </div>
    <%= f.hidden_field :viewable_id %>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label :alt %><br>
    <%= f.text_area :alt, rows: 4, class: 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/offer_images/edit.html.erb
<%= render :partial => 'spree/admin/offers/offer_tabs', :locals => { :current => 'Images' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @offer_image } %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_images_list), admin_offer_images_url(@offer), :icon => 'arrow-left' %></li>
<% end %>

<%= form_for [:admin, @offer, @offer_image], url: admin_offer_image_path(@offer, @offer_image), :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @offer_image.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label Spree.t(:thumbnail) %><br>
      <%= link_to image_tag(@offer_image.attachment.url(:small)), @offer_image.attachment.url(:offer) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <%= link_to Spree.t('actions.cancel'), admin_offer_images_url(@offer), :id => 'cancel_link', :class => 'button remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/offer_images/index.html.erb
<%= render :partial => 'spree/admin/offers/offer_tabs', :locals => {:current => 'Images'} %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Image) %>
    <li><%= link_to_with_icon('plus', Spree.t(:new_image), new_admin_offer_image_url(@offer), :id => 'new_image_link', :class => 'button') %></li>
  <% end %>
<% end %>

<div id="images" data-hook></div>

<% unless @offer.images.any?  %>
  <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_offer_images_url(@offer) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <th><%= Spree::Image.human_attribute_name(:alt) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@offer.images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <% if can?(:update_positions, Spree::Image) %>
              <span class="handle"></span>
            <% end %>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:products) %>
          </td>
          <td><%= image.alt %></td>
          <td class="actions">
            <% if can?(:update, image) %>
              <%= link_to_with_icon 'edit', Spree.t('actions.edit'), edit_admin_offer_image_url(@offer, image), :no_text => true, :data => {:action => 'edit'} %>
            <% end %>
            <% if can?(:destroy, image) %>
              <%= link_to_delete image, { :url => admin_offer_image_url(@offer, image), :no_text => true } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/offer_images/new.html.erb
<% @offer_image.viewable_id = @offer.id %>
<%= form_for [:admin, @offer_image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_image">
    <legend align="center"><%= Spree.t(:new_image) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'refresh' %>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_offer_images_url(@offer), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

app/views/spree/admin/offers/_form.html.erb
<div data-hook="admin_offer_form_fields" class="row">
  <div class="left twelve columns alpha" data-hook="admin_offer_form_left">
    <div data-hook="admin_offer_form_name">
      <%= f.field_container :name do %>
        <%= f.label :name, class: 'required' %>
        <%= f.text_field :name, :class => 'fullwidth title', :required => true %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_slug">
      <%= f.field_container :slug do %>
        <%= f.label :slug, class: 'required' %>
        <%= f.text_field :slug, :class => 'fullwidth title', :required => true %>
        <%= f.error_message_on :slug %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_discount">
      <%= f.field_container :discount do %>
        <%= f.label :discount %>
        <%= f.text_field :discount, { :class => 'fullwidth' } %>
        <%= f.error_message_on :discount %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_taxon">
        <span id="taxon">
          <%= f.label :taxon_id, Spree::Taxon.model_name.human %>
          <%= f.collection_select :taxon_id, @taxons, :first, :last, {}, { :class => 'select2 fullwidth' } %>
        </span>
    </div>

    <div data-hook="admin_offer_form_active">
      <%= f.field_container :active do %>
        <%= f.label :active %>
        <%= f.check_box :active %>
        <%= f.error_message_on :active %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_main">
      <%= f.field_container :active do %>
        <%= f.label :main %>
        <%= f.check_box :main %>
        <%= f.error_message_on :main %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_abstract">
      <%= f.field_container :abstract do %>
        <%= f.label :abstract %>
        <%= f.text_area :abstract, { :rows => "5", :class => 'fullwidth' } %>
        <%= f.error_message_on :abstract %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_description">
      <%= f.field_container :description do %>
        <%= f.label :description %>
        <%= f.text_area :description, { :rows => "10", :class => 'fullwidth' } %>
        <%= f.error_message_on :description %>
      <% end %>
    </div>

  </div>


  <div data-hook="admin_offer_form_meta" class="alpha omega twelve columns">
    <div data-hook="admin_offer_form_meta_title">
      <%= f.field_container :meta_title do %>
        <%= f.label :meta_title %>
        <%= f.text_field :meta_title, :class => 'fullwidth' %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_meta_keywords">
      <%= f.field_container :meta_keywords do %>
        <%= f.label :meta_keywords %>
        <%= f.text_field :meta_keywords, :class => 'fullwidth' %>
      <% end %>
    </div>

    <div data-hook="admin_offer_form_meta_description">
      <%= f.field_container :meta_description do %>
        <%= f.label :meta_description %>
        <%= f.text_field :meta_description, :class => 'fullwidth' %>
      <% end %>
    </div>
  </div>

</div>

app/views/spree/admin/offers/_offer_tabs.html.erb
<% content_for :tabs do %>
  <nav>
    <ul class="tabs" data-hook="admin_product_tabs">
      <%= content_tag :li, :class => ('active' if current == 'Offer Details') do %>
        <%= link_to_with_icon 'edit', Spree.t(:offer_details), spree.edit_admin_offer_url(@offer) %>
      <% end %>
      <%= content_tag :li, :class => ('active' if current == 'Images') do %>
        <%= link_to_with_icon 'picture-o', Spree.t(:images), spree.admin_offer_images_url(@offer) %>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/spree/admin/offers/_tab.html.erb
<% if can? :admin, Spree::Offer %>
  <%= tab :offers, icon: 'bullhorn' %>
<% end %>

app/views/spree/admin/offers/edit.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_offer)} #{@offer.name}", edit_admin_offer_url(@offer) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_offers_list), spree.admin_offers_path, :icon => 'arrow-left' %></li>
  <% if can?(:create, Spree::Offer) %>
    <li id="new_offer_link">
      <%= button_link_to Spree.t(:new_offer), new_object_url, { :icon => 'plus', :id => 'admin_new_offer' } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/admin/offers/offer_tabs', locals: { current: 'Offer Details' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @offer } %>

<div data-hook="admin_offer_new_form">
  <%= form_for [:admin, @offer], url: admin_offer_url(@offer), method: :put do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_offer_new_form_buttons">
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/offers/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_offers) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:admin, Spree::Offer) && can?(:create, Spree::Offer) %>
    <li>
      <%= button_link_to Spree.t(:new_offer), new_admin_offer_url, :icon => 'plus', :id => 'admin_new_offer_link' %>
    </li>
  <% end %>
<% end %>

<table class="index" id="listing_offers" data-hook>
  <!--<colgroup>-->
    <!--<col style="width: 85%">-->
    <!--<col style="width: 15%">-->
  <!--</colgroup>-->
  <thead>
  <tr data-hook="admin_offers_index_headers">
    <th><%= sort_link @search,:name, Spree::Offer.model_name.human, {}, {:title => 'offers_name'} %></th>
    <th><%= sort_link @search,:taxon, Spree::Taxon.model_name.human, {}, {:title => 'offers_taxon'} %></th>
    <th><%= sort_link @search,:discount, Spree.t(:discount), {}, {:title => 'offers_discount'} %></th>
    <th><%= sort_link @search,:active, Spree.t(:active), {}, {:title => 'offers_active'} %></th>
    <th><%= sort_link @search,:affected, Spree.t(:affected), {}, {:title => 'offers_affected'} %></th>
    <th data-hook="admin_offers_index_header_actions" class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @offers.each do |offer|%>
    <tr id="<%= spree_dom_id offer %>" data-hook="admin_offers_index_rows" class="<%= cycle('odd', 'even')%>">
      <td class='offer_name'><%=link_to offer.name, edit_admin_offer_url(offer) %></td>
      <td class='offer_taxon'><%= @taxons.select{|pair| pair.first == offer.taxon.id }.last.last %></td>
      <td class='offer_discount'><%= offer.discount %>%</td>
      <td class='offer_active'><%= offer.active ? Spree.t(:yes) : Spree.t(:no) %></td>
      <td class='offer_affected'><%= offer.taxon.products.count %></td>
      <td data-hook="admin_offers_index_row_actions" class="actions">
        <% if can?(:edit, offer) %>
          <%= link_to_edit offer, :no_text => true %>
        <% end %>
        <% if can?(:destroy, offer) %>
          <%= link_to_delete offer, :no_text => true %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @offers, theme: "solidus_admin" %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
  <div class="box align-center" data-hook="admin_offers_index_search">
    <%= search_form_for [:admin, @search], url: admin_offers_url do |f| %>
      <div class="field">
        <%= f.label :name_cont, Spree.t(:name) %> <br>
        <%= f.text_field :name_cont, :class => 'fullwidth' %>
      </div>
      <div data-hook="admin_offers_index_search_buttons">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/offers/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_offer) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_offers_list), spree.admin_offers_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<div data-hook="admin_offer_new_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @offer } %>
</div>

<div data-hook="admin_offer_new_form">
  <%= form_for [:admin, @offer], url: admin_offers_url, method: :post do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_offer_new_form_buttons">
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/translations/offer.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Offer.model_name.human) %>
<% end %>

<%= render 'settings' %>

<div class="row translations">
  <div class="col-md-4">
    <%= render 'fields' %>
  </div>
  <div class="col-md-8">
    <%= form_for [:admin, @resource] do |f| %>
      <%= render 'form_fields', f: f %>
      <div class="form-actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'refresh', 'submit', {class: 'btn-success'} %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= button_link_to Spree.t('actions.cancel'), spree.edit_admin_offer_path(@resource), icon: 'delete' %>
      </div>
    <% end %>
  </div>
</div>